name: Update Stock Data

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit
  workflow_dispatch:    # Bouton manuel

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      contents: write  # Cette ligne force la permission d'écriture

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install yfinance pandas lxml html5lib requests beautifulsoup4

    - name: Run Screener
      run: |
        # Assurez-vous que le fichier s'appelle bien screener.py
        python screener.py

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data.json
        # On vérifie s'il y a des changements avant de commiter
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data" && git push origin HEAD:main)
